### ISSUE TITLE
Error on using: Package LazyBandedMatrices does not have ArrayLayouts in its dependencies

### ISSUE THREAD

**Issue by ChrisRackauckas** [JuliaMatrices/LazyBandedMatrices.jl#32]
Found in https://github.com/SciML/SciMLBase.jl/runs/1855198388?check_suite_focus=true#step:6:715.

But I don't see the error directly with DiffEqOperators.jl. So my guess is that something in here needs to up the lower bound:

https://github.com/SciML/DiffEqOperators.jl/blob/master/Project.toml#L27

**Comment by dlfivefifty** [comment]
I don't understand this as it clearly does have ArrayLayouts in its dependendices:

https://github.com/JuliaMatrices/LazyBandedMatrices.jl/blob/master/Project.toml

**Comment by ChrisRackauckas** [comment]
Hmm I can't recreate it now.
